name: One Page Scripts

description: Screenplays one page long

url: http://onepagescripts.com

gems:
  - jekyll-sitemap
  
permalink: :title

defaults: 
  - 
    scope: 
      path: "" 
    values: 
      layout: "default" 